server:
 port: 8080
 servlet:
  context-path: /cafe
  
spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: ec2-35-174-35-242.compute-1.amazonaws.com
  username: yswdqpohohucav
  password: 1f5b0f342b6622315df94907b1ed8a2d0270be6a1b25a91a1fe0c705aecd1075  
 jpa:  
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true
  hibernate:
   ddl-auto: none