server:
 port: 8080
 servlet:  context-path: /cafe
  
spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/bootcamp
  username: postgres
  password: 30332692  
 jpa:  
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: false
  hibernate:
   ddl-auto: none